wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707664842.631887
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.3
      6: 4.38.0.dev0
      8:
      - 5
      13: linux-x86_64
